import React from 'react';

export const S = {
  // sidebar
  sidebar: (collapsed: boolean): React.CSSProperties => ({
    width: collapsed ? '44px' : '360px',
    minWidth: collapsed ? '44px' : '360px',
    background: 'var(--sub)',
    borderRight: '2px solid var(--bd)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    transition: 'width 0.2s ease, min-width 0.2s ease',
    position: 'relative',
  }),
  card: (): React.CSSProperties => ({
    background: 'var(--pbg)',
    border: '1.5px solid var(--bd)',
    borderRadius: '16px 12px 18px 14px / 14px 18px 12px 16px',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    boxShadow: 'var(--sh-sm)',
  }),
  sectionTitle: (): React.CSSProperties => ({
    fontSize: '16px',
    fontWeight: 700,
    fontFamily: 'var(--hfont)',
    letterSpacing: '0.02em',
    color: 'var(--act)',
    marginBottom: '2px',
  }),
  label: (indent = false): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12.5px',
    color: 'var(--fg)',
    cursor: 'pointer',
    marginLeft: indent ? '20px' : 0,
    fontFamily: 'var(--font)',
  }),
  badge: (color: string): React.CSSProperties => ({
    fontSize: '10px',
    fontWeight: 700,
    padding: '2px 7px',
    borderRadius: 'var(--rx)',
    background: color === '#374151' ? 'var(--sub)' : color,
    color: color === '#374151' ? 'var(--fg)' : '#fff',
    border: '1px solid var(--bd)',
    marginLeft: 'auto',
  }),
  btn: (primary = false, disabled = false): React.CSSProperties => ({
    padding: primary ? '8px 12px' : '6px 12px',
    flex: primary ? 1 : undefined,
    fontSize: '17px',
    fontWeight: 700,
    fontFamily: 'var(--hfont)',
    borderRadius: '12px 9px 12px 9px',
    border: '1.5px solid var(--bd)',
    background: primary ? (disabled ? 'var(--mute)' : 'var(--ac)') : 'var(--pbg)',
    color: primary ? (disabled ? 'var(--sub)' : 'var(--acfg)') : 'var(--fg)',
    cursor: disabled ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    opacity: disabled ? 0.6 : 1,
    boxShadow: disabled ? 'none' : '2px 2px 0 var(--bd)',
    transition: 'all 0.15s',
  }),
  select: (): React.CSSProperties => ({
    width: '100%',
    padding: '6px 8px',
    fontSize: '12.5px',
    borderRadius: 'var(--rs)',
    border: '1.5px solid var(--bd)',
    background: 'var(--sub)',
    color: 'var(--fg)',
    fontFamily: 'var(--font)',
  }),
  filterInput: (): React.CSSProperties => ({
    width: '100%',
    padding: '6px 8px',
    fontSize: '12px',
    borderRadius: 'var(--rs)',
    border: '1.5px solid var(--bd)',
    background: 'var(--sub)',
    color: 'var(--fg)',
    boxSizing: 'border-box' as const,
    fontFamily: 'var(--font)',
  }),
  listBox: (): React.CSSProperties => ({
    maxHeight: '160px',
    overflowY: 'auto' as const,
    background: 'var(--pbg)',
    border: '1.5px solid var(--bd)',
    borderRadius: 'var(--rs)',
    padding: '4px',
  }),
  listRow: (error = false): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: '6px',
    fontSize: '11.5px',
    padding: '3px 4px',
    borderRadius: '4px',
    cursor: 'pointer',
    color: error ? 'var(--er)' : 'var(--fg)',
  }),
  collapseBtn: (): React.CSSProperties => ({
    position: 'absolute' as const,
    top: '50%',
    right: '-12px',
    transform: 'translateY(-50%)',
    width: '24px',
    height: '40px',
    background: 'var(--sub)',
    border: '1.5px solid var(--bd)',
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--fg)',
    boxShadow: '1.5px 1.5px 0 var(--bd)',
    zIndex: 10,
    padding: 0,
  }),
};
